In [2]:
import tensorflow as tf
import sys

In [3]:
print(f'wersja tensorflow: {tf.__version__}')
print(f'wersja pythona: {sys.version_info}')

wersja tensorflow: 2.13.1
wersja pythona: sys.version_info(major=3, minor=8, micro=20, releaselevel='final', serial=0)


In [4]:
#ładowanie danych ze zbioru mnist
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()

#normalizacja danych
x_train,x_test = x_train/255.0,x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [5]:
#prosty model sieci neuronowej
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
print(predictions)

[[-0.74347836  0.56287825  0.11250807 -0.22138663 -0.67000544  0.46721777
  -0.2884376  -0.7595928  -0.35002342 -0.48827958]]


In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.05406263, 0.19963685, 0.12724696, 0.09112526, 0.05818434,
 0.18142448, 0.08521556, 0.05319843, 0.08012584, 0.06977963]],
 dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101770 (397.54 KB)
Trainable params: 101770 (397.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.3005 - accuracy: 0.9129
Epoch 2/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1440 - accuracy: 0.9574
Epoch 3/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1078 - accuracy: 0.9680
Epoch 4/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0889 - accuracy: 0.9729
Epoch 5/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0749 - accuracy: 0.9766
Epoch 6/20
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0660 - accuracy: 0.9791
Epoch 7/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0579 - accuracy: 0.9816
Epoch 8/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0534 - accuracy: 0.9823
Epoch 9/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0478 - accuracy: 0.9845
Epoch 10/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.043

In [10]:
#ocena modelu
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0777 - accuracy: 0.9811 - 1s/epoch - 4ms/step


[0.07769905775785446, 0.9811000227928162]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.3964894e-11, 6.8050600e-14, 1.0517327e-10, 1.4783050e-06,
        3.9522659e-15, 8.4256095e-11, 1.7357270e-19, 9.9999857e-01,
        1.5509919e-08, 8.0795033e-09],
       [4.7169716e-14, 1.2423076e-11, 1.0000000e+00, 1.1387125e-11,
        2.0588631e-35, 6.3587309e-11, 2.9907804e-13, 5.8587136e-28,
        9.3269836e-12, 9.0110763e-25],
       [7.7977402e-10, 9.9942446e-01, 1.6069687e-05, 5.0732422e-07,
        2.1220735e-08, 5.7883072e-09, 2.1468427e-06, 2.8822714e-04,
        2.6871104e-04, 6.9570922e-09],
       [1.0000000e+00, 5.1002379e-16, 3.0931094e-08, 3.9769728e-13,
        4.1364678e-14, 5.3189242e-10, 7.8868156e-09, 1.9879651e-10,
        2.9268465e-14, 2.3126672e-08],
       [1.1210878e-10, 3.0676750e-25, 2.3761601e-10, 1.1214224e-12,
        9.9999523e-01, 7.4792040e-14, 3.7744794e-13, 2.5741608e-07,
        8.0269585e-13, 4.5539841e-06]], dtype=float32)>

In [13]:
import numpy as np

In [14]:
w1 = probability_model(x_test[:1])
np.argmax(w1)

7

In [15]:
y_test[:1]

array([7], dtype=uint8)