In [3]:
print("to jest pierwsza komórka!")
a = 15

to jest pierwsza komórka!


In [4]:
print(a)

15


To jest pierwszy **Notebook** oparty na <span style="color:red; font-size:16pt">Jupyter Notebook</span>

In [18]:
ilosc = 15

In [16]:
cena = "chleb"

In [19]:
if cena == "chleb":
    cena = 7.3
cena_calk = cena*ilosc
cena_calk

109.5

In [22]:
# !pip install numpy==2.1

In [20]:
import numpy as np

In [21]:
print(np.__version__)

1.24.4


In [23]:
lista = [54,532,245,8,2,57,-353,2,0,78,-98]
ar = np.array(lista)

In [24]:
print(f"lista (typ -> {type(lista)}): {lista}")
print(f"lista (typ -> {type(ar)}): {ar}")

lista (typ -> <class 'list'>): [54, 532, 245, 8, 2, 57, -353, 2, 0, 78, -98]
lista (typ -> <class 'numpy.ndarray'>): [  54  532  245    8    2   57 -353    2    0   78  -98]


In [25]:
np.array([6,7,2,7,2])

array([6, 7, 2, 7, 2])

In [26]:
ts = np.linspace(0.0,9.99,1000)
ts

array([0. , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
 0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
 0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
 0.99, 1. , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
 1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
 1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
 1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
 1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53,
 1.54, 1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64,
 1.65, 1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75,
 1.76, 1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86,
 1.87, 1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97,
 1.98, 1.99, 2. , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08,
 2.09, 2.1 , 2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19,
 2.2 , 2.21, 2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 ,
 2.31, 2.32, 2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41,
 2.42, 2.43, 2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 2.51, 2.52,
 2.53, 2.54, 2.55, 2.56, 2.57, 2.58, 2.59, 2.6 , 2.61, 2.62, 2.63,
 2.64, 2.65, 2.66, 2.67, 2.68, 2.69, 2.7 , 2.71, 2.72, 2.73, 2.74,
 2.75, 2.76, 2.77, 2.78, 2.79, 2.8 , 2.81, 2.82, 2.83, 2.84, 2.85,
 2.86, 2.87, 2.88, 2.89, 2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96,
 2.97, 2.98, 2.99, 3. , 3.01, 3.02, 3.03, 3.04, 3.05, 3.06, 3.07,
 3.08, 3.09, 3.1 , 3.11, 3.12, 3.13, 3.14, 3.15, 3.16, 3.17, 3.18,
 3.19, 3.2 , 3.21, 3.22, 3.23, 3.24, 3.25, 3.26, 3.27, 3.28, 3.29,
 3.3 , 3.31, 3.32, 3.33, 3.34, 3.35, 3.36, 3.37, 3.38, 3.39, 3.4 ,
 3.41, 3.42, 3.43, 3.44, 3.45, 3.46, 3.47, 3.48, 3.49, 3.5 , 3.51,
 3.52, 3.53, 3.54, 3.55, 3.56, 3.57, 3.58, 3.59, 3.6 , 3.61, 3.62,
 3.63, 3.64, 3.65, 3.66, 3.67, 3.68, 3.69, 3.7 , 3.71, 3.72, 3.73,
 3.74, 3.75, 3.76, 3.77, 3.78, 3.79, 3.8 , 3.81, 3.82, 3.83, 3.84,
 3.85, 3.86, 3.87, 3.88, 3.89, 3.9 , 3.91, 3.92, 3.93, 3.94, 3.95,
 3.96, 3.97, 3.98, 3.99, 4. , 4.01, 4.02, 4.03, 4.04, 4.05, 4.06,
 4.07, 4.08, 4.09, 4.1 , 4.11, 4.12, 4.13, 4.14, 4.15, 4.16, 4.17,
 4.18, 4.19, 4.2 , 4.21, 4.22, 4.23, 4.24, 4.25, 4.26, 4.27, 4.28,
 4.29, 4.3 , 4.31, 4.32, 4.33, 4.34, 4.35, 4.36, 4.37, 4.38, 4.39,
 4.4 , 4.41, 4.42, 4.43, 4.44, 4.45, 4.46, 4.47, 4.48, 4.49, 4.5 ,
 4.51, 4.52, 4.53, 4.54, 4.55, 4.56, 4.57, 4.58, 4.59, 4.6 , 4.61,
 4.62, 4.63, 4.64, 4.65, 4.66, 4.67, 4.68, 4.69, 4.7 , 4.71, 4.72,
 4.73, 4.74, 4.75, 4.76, 4.77, 4.78, 4.79, 4.8 , 4.81, 4.82, 4.83,
 4.84, 4.85, 4.86, 4.87, 4.88, 4.89, 4.9 , 4.91, 4.92, 4.93, 4.94,
 4.95, 4.96, 4.97, 4.98, 4.99, 5. , 5.01, 5.02, 5.03, 5.04, 5.05,
 5.06, 5.07, 5.08, 5.09, 5.1 , 5.11, 5.12, 5.13, 5.14, 5.15, 5.16,
 5.17, 5.18, 5.19, 5.2 , 5.21, 5.22, 5.23, 5.24, 5.25, 5.26, 5.27,
 5.28, 5.29, 5.3 , 5.31, 5.32, 5.33, 5.34, 5.35, 5.36, 5.37, 5.38,
 5.39, 5.4 , 5.41, 5.42, 5.43, 5.44, 5.45, 5.46, 5.47, 5.48, 5.49,
 5.5 , 5.51, 5.52, 5.53, 5.54, 5.55, 5.56, 5.57, 5.58, 5.59, 5.6 ,
 5.61, 5.62, 5.63, 5.64, 5.65, 5.66, 5.67, 5.68, 5.69, 5.7 , 5.71,
 5.72, 5.73, 5.74, 5.75, 5.76, 5.77, 5.78, 5.79, 5.8 , 5.81, 5.82,
 5.83, 5.84, 5.85, 5.86, 5.87, 5.88, 5.89, 5.9 , 5.91, 5.92, 5.93,
 5.94, 5.95, 5.96, 5.97, 5.98, 5.99, 6. , 6.01, 6.02, 6.03, 6.04,
 6.05, 6.06, 6.07, 6.08, 6.09, 6.1 , 6.11, 6.12, 6.13, 6.14, 6.15,
 6.16, 6.17, 6.18, 6.19, 6.2 , 6.21, 6.22, 6.23, 6.24, 6.25, 6.26,
 6.27, 6.28, 6.29, 6.3 , 6.31, 6.32, 6.33, 6.34, 6.35, 6.36, 6.37,
 6.38, 6.39, 6.4 , 6.41, 6.42, 6.43, 6.44, 6.45, 6.46, 6.47, 6.48,
 6.49, 6.5 , 6.51, 6.52, 6.53, 6.54, 6.55, 6.56,

In [27]:
%%time
67*ts

CPU times: user 742 µs, sys: 0 ns, total: 742 µs
Wall time: 1.02 ms


array([ 0. , 0.67, 1.34, 2.01, 2.68, 3.35, 4.02, 4.69,
 5.36, 6.03, 6.7 , 7.37, 8.04, 8.71, 9.38, 10.05,
 10.72, 11.39, 12.06, 12.73, 13.4 , 14.07, 14.74, 15.41,
 16.08, 16.75, 17.42, 18.09, 18.76, 19.43, 20.1 , 20.77,
 21.44, 22.11, 22.78, 23.45, 24.12, 24.79, 25.46, 26.13,
 26.8 , 27.47, 28.14, 28.81, 29.48, 30.15, 30.82, 31.49,
 32.16, 32.83, 33.5 , 34.17, 34.84, 35.51, 36.18, 36.85,
 37.52, 38.19, 38.86, 39.53, 40.2 , 40.87, 41.54, 42.21,
 42.88, 43.55, 44.22, 44.89, 45.56, 46.23, 46.9 , 47.57,
 48.24, 48.91, 49.58, 50.25, 50.92, 51.59, 52.26, 52.93,
 53.6 , 54.27, 54.94, 55.61, 56.28, 56.95, 57.62, 58.29,
 58.96, 59.63, 60.3 , 60.97, 61.64, 62.31, 62.98, 63.65,
 64.32, 64.99, 65.66, 66.33, 67. , 67.67, 68.34, 69.01,
 69.68, 70.35, 71.02, 71.69, 72.36, 73.03, 73.7 , 74.37,
 75.04, 75.71, 76.38, 77.05, 77.72, 78.39, 79.06, 79.73,
 80.4 , 81.07, 81.74, 82.41, 83.08, 83.75, 84.42, 85.09,
 85.76, 86.43, 87.1 , 87.77, 88.44, 89.11, 89.78, 90.45,
 91.12, 91.79, 92.46, 93.13, 93.8 , 94.47, 95.14, 95.81,
 96.48, 97.15, 97.82, 98.49, 99.16, 99.83, 100.5 , 101.17,
 101.84, 102.51, 103.18, 103.85, 104.52, 105.19, 105.86, 106.53,
 107.2 , 107.87, 108.54, 109.21, 109.88, 110.55, 111.22, 111.89,
 112.56, 113.23, 113.9 , 114.57, 115.24, 115.91, 116.58, 117.25,
 117.92, 118.59, 119.26, 119.93, 120.6 , 121.27, 121.94, 122.61,
 123.28, 123.95, 124.62, 125.29, 125.96, 126.63, 127.3 , 127.97,
 128.64, 129.31, 129.98, 130.65, 131.32, 131.99, 132.66, 133.33,
 134. , 134.67, 135.34, 136.01, 136.68, 137.35, 138.02, 138.69,
 139.36, 140.03, 140.7 , 141.37, 142.04, 142.71, 143.38, 144.05,
 144.72, 145.39, 146.06, 146.73, 147.4 , 148.07, 148.74, 149.41,
 150.08, 150.75, 151.42, 152.09, 152.76, 153.43, 154.1 , 154.77,
 155.44, 156.11, 156.78, 157.45, 158.12, 158.79, 159.46, 160.13,
 160.8 , 161.47, 162.14, 162.81, 163.48, 164.15, 164.82, 165.49,
 166.16, 166.83, 167.5 , 168.17, 168.84, 169.51, 170.18, 170.85,
 171.52, 172.19, 172.86, 173.53, 174.2 , 174.87, 175.54, 176.21,
 176.88, 177.55, 178.22, 178.89, 179.56, 180.23, 180.9 , 181.57,
 182.24, 182.91, 183.58, 184.25, 184.92, 185.59, 186.26, 186.93,
 187.6 , 188.27, 188.94, 189.61, 190.28, 190.95, 191.62, 192.29,
 192.96, 193.63, 194.3 , 194.97, 195.64, 196.31, 196.98, 197.65,
 198.32, 198.99, 199.66, 200.33, 201. , 201.67, 202.34, 203.01,
 203.68, 204.35, 205.02, 205.69, 206.36, 207.03, 207.7 , 208.37,
 209.04, 209.71, 210.38, 211.05, 211.72, 212.39, 213.06, 213.73,
 214.4 , 215.07, 215.74, 216.41, 217.08, 217.75, 218.42, 219.09,
 219.76, 220.43, 221.1 , 221.77, 222.44, 223.11, 223.78, 224.45,
 225.12, 225.79, 226.46, 227.13, 227.8 , 228.47, 229.14, 229.81,
 230.48, 231.15, 231.82, 232.49, 233.16, 233.83, 234.5 , 235.17,
 235.84, 236.51, 237.18, 237.85, 238.52, 239.19, 239.86, 240.53,
 241.2 , 241.87, 242.54, 243.21, 243.88, 244.55, 245.22, 245.89,
 246.56, 247.23, 247.9 , 248.57, 249.24, 249.91, 250.58, 251.25,
 251.92, 252.59, 253.26, 253.93, 254.6 , 255.27, 255.94, 256.61,
 257.28, 257.95, 258.62, 259.29, 259.96, 260.63, 261.3 , 261.97,
 262.64, 263.31, 263.98, 264.65, 265.32, 265.99, 266.66, 267.33,
 268. , 268.67, 269.34, 270.01, 270.68, 271.35, 272.02, 272.69,
 273.36, 274.03, 274.7 , 275.37, 276.04, 276.71, 277.38, 278.05,
 278.72, 279.39, 280.06, 280.73, 281.4 , 282.07, 282.74, 283.41,
 284.08, 284.75, 285.42, 286.09, 286.76, 287.43, 288.1 , 288.77,
 289.44, 290.11, 290.78, 291.45, 292.12, 292.79, 293.46, 294.13,
 294.8 , 295.47, 296.14, 296.81, 297.48, 298.15, 298.82, 299.49,
 300.16, 300.83, 301.5 , 302.17, 302.84, 303.51, 304.18, 304.85,
 305.52, 306.19, 306.86, 307.53, 308.2 , 308.87, 309.54, 310.21,
 310.88, 311.55, 312.22, 312.89, 313.56, 314.23, 314.9 , 315.57,
 316.24, 316.91, 317.58, 318.25, 318.92, 319.59, 320.26, 320.93,
 321.6 , 322.27, 322.94, 323.61, 324.28, 324.95, 325.62, 326.29,
 326.96, 327.63, 328.3 , 328.97, 329.64, 330.31, 330.98, 331.65,
 332.32, 332.99, 333.66, 334.33, 335. , 335.67, 336.34, 337.01,
 337.68, 338.35, 339.02, 339.69, 340.36, 341.03, 341.7 , 342.37,
 343

In [28]:
np.arange(16_000_000)

array([ 0, 1, 2, ..., 15999997, 15999998, 15999999])

In [29]:
w = np.array([[1,2,3],[6,3,56],[98,12,77]])
w

array([[ 1, 2, 3],
 [ 6, 3, 56],
 [98, 12, 77]])

In [30]:
zwlist = [[1,5,7],[4,3,3],[9,11,34]]
zwlist

[[1, 5, 7], [4, 3, 3], [9, 11, 34]]

In [34]:
zwlist[1][0]

4

In [35]:
w[0][1]

2

In [36]:
w[0,1]

2

In [37]:
w[w<5]

array([1, 2, 3, 3])

In [38]:
pc = (w>16)
w[pc]

array([56, 98, 77])

In [39]:
lg = (w%2==0)
w[lg]

array([ 2, 6, 56, 98, 12])

In [40]:
sv = w[(w>2)&(w<=32)]
sv

array([ 3, 6, 3, 12])

In [41]:
l1 = [5,2,8,3]
l2 = [45,6,2.34,2.45]

lw = l1+l2
lw

[5, 2, 8, 3, 45, 6, 2.34, 2.45]

In [42]:
npl1 = np.array([4,2,7,8])
npl2 = np.array([7.5,3,23.4,2.34])

npl = npl1 + npl2
npl

array([11.5 , 5. , 30.4 , 10.34])

In [44]:
npl = npl1*npl2
npl

array([ 30. , 6. , 163.8 , 18.72])

In [46]:
nplcon = np.concatenate((npl1,npl2))
nplcon

array([ 4. , 2. , 7. , 8. , 7.5 , 3. , 23.4 , 2.34])

In [56]:
arten = np.arange(24).reshape((4,6))
arten

array([[ 0, 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]])

In [57]:
tens3D = np.arange(27).reshape((3,3,3))
tens3D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [59]:
dane8D = np.arange(15552).reshape((2,2,2,3,3,3,8,9))
dane8D

array([[[[[[[[    0,     1,     2, ...,     6,     7,     8],
             [    9,    10,    11, ...,    15,    16,    17],
             [   18,    19,    20, ...,    24,    25,    26],
             ...,
             [   45,    46,    47, ...,    51,    52,    53],
             [   54,    55,    56, ...,    60,    61,    62],
             [   63,    64,    65, ...,    69,    70,    71]],

            [[   72,    73,    74, ...,    78,    79,    80],
             [   81,    82,    83, ...,    87,    88,    89],
             [   90,    91,    92, ...,    96,    97,    98],
             ...,
             [  117,   118,   119, ...,   123,   124,   125],
             [  126,   127,   128, ...,   132,   133,   134],
             [  135,   136,   137, ...,   141,   142,   143]],

            [[  144,   145,   146, ...,   150,   151,   152],
             [  153,   154,   155, ...,   159,   160,   161],
             [  162,   163,   164, ...,   168,   169,   170],
             ...,
            